env:
  global:
    - CC_TEST_REPORTER_ID=cd374ecebbc117b8a6055a17a56200ae87f61844d2c34893eaa0be55e3abf628
language: ruby
rvm:
  - 2.2.0
  - 2.4.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  